version: "3.3"

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "fish-stories-db"
      # So you don't have to use root, but you can if you like
      MYSQL_ROOT_PASSWORD: "pa55word"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    container_name: mysqldb

  app:
    image: elgunner79/fish-stories:latest
    restart: always
    environment:
      PORT: 3001
      DB_HOST: 'mysqldb'
      DB_USER: 'root'
      DB_PASS: 'pa55word'
      DB_NAME: 'fish-stories-db'
      DB_SSL: 'false'
      BASE_URL: 'http://localhost:3001'
    depends_on:
      mysqldb:
        condition: service_started
    ports:
      - '3001:3001'
    container_name: app